### ISSUE TITLE
Directory issue

### ISSUE THREAD

**Issue by LocalBoomer** [NoiSek/Sound-Alert#1]
I doubt anyone is still monitoring this but hey ho,

Whenever I load the plugin with a sound file in both my share and sounds folder it won't load it and whenever I try to set a directory with the set command it says invalid directory. Any ideas why?

**Comment by NoiSek** [comment]
This should be fixed between 6e72c5af6e7cfd4191f1970ee4cef5ee3eff08de and 386ade0dde8ef975a6b4d6badfb39bea35279fdc.
