### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by LocalBoomer** [NoiSek/Sound-Alert#2]
Sound Alert plugin loaded.
 Traceback (most recent call last):
   File "<string>", line 137, in <module>
   File "<string>", line 29, in **init**
   File "<string>", line 79, in find_sound_directory
 TypeError: _isdir: can't specify None for path argument
 Error loading module C:\Users<my username>\AppData\Roaming\HexChat\addons\soundalert.py

I get this error when I try to load the plugin now

(using python version  1.0/3/5 (I assume this means I have dualbooted the plugins somehow) and HexChat version 2.12.1)

**Comment by NoiSek** [comment]
No fault on your end, this should fix it 685c398d44263e08f10e8a9bc7eadd7f7ad40ecb.
