### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by LocalBoomer** [NoiSek/Sound-Alert#4]
Whenever I launch HexChat and Soundalert loads it doesn't play any sounds when it should. If I test it it plays a default windows sound but if I reload the plugin it seems to work fine.

**Comment by NoiSek** [comment]
Should be solved by the latest at https://github.com/NoiSek/Sound-Alert/commit/4169450315b0c0e2f1734fe4ce70128239c2e10e, appears the sound directory was being changed after the plugin had already switched on startup.
